name: Purge CDN Cache

on: 
  push:
    branches:
      - main
  # schedule:
  #   - cron:  '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Tar and Hash
      run: |
        tar -cvf git.tar *.yaml
        echo "::set-env name=GITMD5::`md5sum git.tar | awk '{ print $1 }'`"
        rm -rf git.tar
    - name: Set up Python 2.2.2
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 2.2.2

    - name: Get Script
      run: |
        wget https://raw.githubusercontent.com/aozaki-kuro/ruleset/main/.github/workflows/purge.py
        wget https://raw.githubusercontent.com/aozaki-kuro/ruleset/main/.github/workflows/jsdelivr_dl.py
        pip install requests
        chmod +x purge.py jsdelivr_dl.py
        
    - name: Run Python Script
      run: python purge.py
